version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: library_management_989j_user
      POSTGRES_PASSWORD: BLJT7OlWGyred1mVXfDtXlmsrgvcCPfq
      POSTGRES_DB: library_management_989j
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  app:
    build: .
    container_name: nextjs_app
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://library_management_989j_user:BLJT7OlWGyred1mVXfDtXlmsrgvcCPfq@dpg-cusl8trqf0us739lfnsg-a.oregon-postgres.render.com/library_management_989j

      - LOG_FILE_PATH=/logs/app.log
    volumes:
      - ./logs:/logs
      - ./prisma:/app/prisma
    restart: always

volumes:
  pgdata:
